force-app/main/default/objects/Image__c/Image__c.object-meta.xml
<CustomObject>
    <label>Image</label>
    <nameField>
        <label>Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Image__c/fields/Album_Id__c.field-meta.xml
<CustomField>
    <fullName>Album_Id__c</fullName>
    <label>Album Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Image__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Image__c/fields/Thumbnail_URL__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_URL__c</fullName>
    <label>Thumbnail URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    public static List<Image__c> createImages(){
        Image__c existingImage = new Image__c(
            Name = 'test',
            Source_Id__c = '1',
            Album_Id__c = '1',
            URL__c = 'https://www.test.test/',
            Thumbnail_URL__c = 'https://www.test.test/'
        );

        Image__c imageToDelete = new Image__c(
            Name = 'test to delete',
            Source_Id__c = '2',
            Album_Id__c = '1',
            URL__c = 'https://www.test.test/',
            Thumbnail_URL__c = 'https://www.test.test/'
        );

        List<Image__c> images = new List<Image__c>{existingImage, imageToDelete};
        insert images;
        return images;
    }
}