force-app/main/default/objects/Image__c/Image__c.object-meta.xml
<CustomObject>
    <label>Image</label>
    <nameField>
        <label>Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Image__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ImageUpsertBatch.cls
global class ImageUpsertBatch implements Database.batchable<Image__c>{
    global List<Image__c> newImages;

    global List<Image__c> start(Database.BatchableContext info){
        return newImages;
    }    

    global void execute(Database.BatchableContext info, List<Image__c> scope){        
        Database.upsert(scope, Image__c.Fields.Source_Id__c, false);
    }  

    global void finish(Database.BatchableContext info){
        List<String> sourceIds = new List<String>();
        for(Image__c image : newImages){
            sourceIds.add(image.Source_Id__c);
        }
        ImageDeleteBatch deleteBatch = new ImageDeleteBatch();
        deleteBatch.newImagesSourceIds = sourceIds;
        Database.executeBatch(deleteBatch);
    }
}