force-app/main/default/objects/Image__c/Image__c.object-meta.xml
<CustomObject>
    <label>Image</label>
    <nameField>
        <label>Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Image__c/fields/Album_Id__c.field-meta.xml
<CustomField>
    <fullName>Album_Id__c</fullName>
    <label>Album Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Image__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Image__c/fields/Thumbnail_URL__c.field-meta.xml
<CustomField>
    <fullName>Thumbnail_URL__c</fullName>
    <label>Thumbnail URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/RestCalloutService.cls
public with sharing class RestCalloutService {

    public static List<ImageWrapper> getImagesInfo(){
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://jsonplaceholder.typicode.com/photos');
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200) {
            List<ImageWrapper> results = (List<ImageWrapper>) JSON.deserialize(response.getBody(), List<ImageWrapper>.class);
            return results;
        } else{
            System.debug('Error ' + response.getStatusCode());
            return null;
        }
    }

    public class ImageWrapper{
        public String albumId {get; set;}
        public String id {get; set;}
        public String title {get; set;}
        public String url {get; set;}
        public String thumbnailUrl {get; set;}

        public Image__c getImage(){
            return new Image__c(
                Name = this.title,
                Source_Id__c = this.id,
                Album_Id__c = this.albumId,
                URL__c = this.url,
                Thumbnail_URL__c = this.thumbnailUrl
            );
        }
    }
}