force-app/main/default/objects/Image__c/Image__c.object-meta.xml
<CustomObject>
    <label>Image</label>
    <nameField>
        <label>Image Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Image__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <externalId>true</externalId>
    <label>Source Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ImageDeleteBatch.cls
global class ImageDeleteBatch implements Database.batchable<SObject> {
    global List<String> newImagesSourceIds;

    global Database.QueryLocator start(Database.BatchableContext info){
        return Database.getQueryLocator('SELECT Id FROM Image__c WHERE Source_Id__c NOT IN :newImagesSourceIds');
    }    

    global void execute(Database.BatchableContext info, List<Image__c> scope){        
        Database.delete(scope, false);
    }  

    global void finish(Database.BatchableContext info){

    }
}